name: Deploy Commands

on:
    push:
        branches:
            - master
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: false

jobs:
    deploy:
        name: Upload to R2
        runs-on: ubuntu-latest
        environment: Production
        env:
            AWS_ACCESS_KEY_ID: ${{ vars.CLOUDFLARE_R2_CDN_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_CDN_SECRET }}
            AWS_DEFAULT_REGION: auto
            CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
            CLOUDFLARE_R2_CDN_BUCKET: ${{ vars.CLOUDFLARE_R2_CDN_BUCKET }}
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Upload shell files to R2
              run: |
                  aws s3 sync . s3://$CLOUDFLARE_R2_CDN_BUCKET/shells/ \
                    --endpoint-url "https://$CLOUDFLARE_ACCOUNT_ID.r2.cloudflarestorage.com" \
                    --exclude "*" \
                    --include "install.sh" \
                    --include "ssm.sh"
